import test from 'node:test';
import assert from 'node:assert/strict';
import { FRANCHISES } from './franchises.js';
import { franchiseCard, franchiseRow, franchiseSpan, firstUnfinishedIndex } from './tv-franchises.mjs';

const part = (id, date, extra = {}) => ({ id, title: `Part ${id}`, release_date: date, poster_path: `/p${id}.jpg`, backdrop_path: `/b${id}.jpg`, vote_average: 7, vote_count: 900, ...extra });
const matrix = { id: 'franchise:2344', collectionId: 2344, title: 'The Matrix', overview: 'Wake up.', backdrop_path: '/m.jpg', poster_path: '/mp.jpg', parts: [part(1, '1999-03-31'), part(2, '2003-05-15'), part(3, '2003-11-05')] };

test('franchiseSpan: how many films and over which years', () => {
  assert.deepEqual(franchiseSpan(matrix), { count: 3, from: 1999, to: 2003, label: '3 films  ·  1999-2003' });
  assert.equal(franchiseSpan({ parts: [part(1, '2001-01-01'), part(2, '2001-12-01')] }).label, '2 films  ·  2001', 'one year is not a range');
  assert.equal(franchiseSpan({ parts: [part(1, '2001-01-01')] }).label, '1 film  ·  2001', 'singular');
});

test('franchiseCard: a tile that carries its franchise and is not mistaken for a film', () => {
  const card = franchiseCard(matrix);
  assert.equal(card.id, 'franchise:2344');
  assert.equal(card.title, 'The Matrix');
  assert.equal(card.media_type, 'franchise');
  assert.equal(card.franchise, matrix);
  assert.equal(card.backdrop_path, '/m.jpg');
  assert.equal(card.release_date, '1999-03-31', 'sorts/ages by its first film');
  assert.equal(card.vote_average, 0, 'no star rating on a franchise tile: it shows its film count instead');
  assert.equal(card.filmCount, 3);
});

test('franchiseRow: on the All and Movies homes only, never on TV, never empty', () => {
  const row = franchiseRow('all', [matrix]);
  assert.equal(row.key, 'franchises');
  assert.equal(row.title, 'Franchises');
  assert.equal(row.items.length, 1);
  assert.equal(row.items[0].media_type, 'franchise');
  assert.equal(row.noSort, true, 'curated order (most popular series first): the generic row sort by rating must not reorder it');
  assert.ok(franchiseRow('movie', [matrix]));
  assert.equal(franchiseRow('tv', [matrix]), null, 'series are not films');
  assert.equal(franchiseRow('live', [matrix]), null);
  assert.equal(franchiseRow('all', []), null);
  assert.equal(franchiseRow('all', undefined), null);
});

test('firstUnfinishedIndex: opens on the next part you have not finished', () => {
  const progress = map => id => map[id] || 0;
  assert.equal(firstUnfinishedIndex(matrix.parts, progress({})), 0, 'nothing watched: Part 1');
  assert.equal(firstUnfinishedIndex(matrix.parts, progress({ 1: 0.97 })), 1, 'Part 1 finished: Part 2');
  assert.equal(firstUnfinishedIndex(matrix.parts, progress({ 1: 0.98, 2: 0.4 })), 1, 'halfway through Part 2: stay on it');
  assert.equal(firstUnfinishedIndex(matrix.parts, progress({ 1: 0.99, 2: 0.99, 3: 0.99 })), 0, 'all finished: start again');
  assert.equal(firstUnfinishedIndex(matrix.parts, undefined), 0, 'no progress source');
});

// ---- the baked data (franchises.js, generated by scripts/build-franchises.mjs) ----
test('franchises.js: the series the user asked for are there, in order, complete enough to trust', () => {
  assert.ok(FRANCHISES.length >= 60, `expected a full catalogue, got ${FRANCHISES.length}`);
  const byTitle = Object.fromEntries(FRANCHISES.map(f => [f.title, f]));
  for (const t of ['Fast & Furious', 'The Matrix', 'Shrek', 'Harry Potter', 'Star Wars', 'The Lord of the Rings', 'Marvel Cinematic Universe', 'James Bond']) assert.ok(byTitle[t], `${t} is listed`);
  assert.ok(byTitle['Fast & Furious'].parts.length >= 10);
  assert.deepEqual(byTitle['The Matrix'].parts.slice(0, 3).map(p => p.title), ['The Matrix', 'The Matrix Reloaded', 'The Matrix Revolutions'], 'Part 1, 2, 3 in release order');
  assert.deepEqual(byTitle['Shrek'].parts.slice(0, 3).map(p => p.title), ['Shrek', 'Shrek 2', 'Shrek the Third']);
  const mcu = byTitle['Marvel Cinematic Universe'];
  assert.ok(mcu.parts.length >= 35, `the MCU has ${mcu.parts.length} films`);
  assert.deepEqual(mcu.parts.slice(0, 3).map(p => p.title), ['Iron Man', 'The Incredible Hulk', 'Iron Man 2']);
  for (const junk of ['Ultimate Avengers 2', 'Ghost Rider', 'Team Thor', 'Groot Takes a Bath']) assert.ok(!mcu.parts.some(p => p.title === junk), `${junk} is not an MCU film`);
});

test('franchises.js: every franchise is well formed (a wrong regeneration must fail loudly)', () => {
  const ids = new Set(); const titles = new Set(); const today = new Date().toISOString().slice(0, 10);
  for (const f of FRANCHISES) {
    assert.match(String(f.id), /^franchise:/);
    assert.ok(!ids.has(f.id) && !titles.has(f.title), `${f.title}: duplicate`);
    ids.add(f.id); titles.add(f.title);
    assert.ok(f.poster_path && f.backdrop_path, `${f.title}: artwork`);
    assert.ok(f.parts.length >= 3, `${f.title}: a franchise has at least 3 films`);
    const partIds = new Set();
    f.parts.forEach((p, i) => {
      assert.ok(p.id && p.title && p.poster_path, `${f.title} part ${i + 1}: id, title, poster`);
      assert.ok(!partIds.has(p.id), `${f.title}: part ${p.title} repeated`);
      partIds.add(p.id);
      assert.ok(p.release_date <= today, `${f.title}: ${p.title} is not released yet`);
      if (i) assert.ok(f.parts[i - 1].release_date <= p.release_date, `${f.title}: parts out of release order at ${p.title}`);
    });
  }
});
